spring:
  datasource:
    url: jdbc:h2:mem:testdb  # H2 in-memory database URL
    driver-class-name: org.h2.Driver
    username: sa             # Default username
    password:                # Default password
  jpa:
#      show-sql: true
    hibernate:
      ddl-auto: create
        # create, update, create-drop, none 등의 옵션이 있습니다.
        #        # create: 기존테이블 삭제 후 다시 생성
        #        # update: 변경된 부분만 반영
        #        # create-drop: create와 같으나 종료 시점에 테이블 DROP
        #        # none: 사용하지 않음
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 1000

  # file upload max size
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 10MB

  jackson:
    timeZone: Asia/Seoul
    dateFormat: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springboot:
  jwt:
    secret: oneulnailTokenKey1234567890qwertyasdfgWHDGKQTJFRPVMFHWPRXMwhdgkqtjfrPvmfhwprxm

logging:
  level:
    org.hibernate.SQL: debug